name: lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Stamp a temporary chart version
        run: sed -i "s/CHART_VERSION/0.0.0-ci/g" ./chart/Chart.yaml

      - name: Lint
        run: helm lint ./chart

      - name: Render (default values)
        run: helm template rancher ./chart --namespace cattle-system > /dev/null

  lint-docs:
    uses: krateo-platformops/.github/.github/workflows/lint-docs.yaml@main
